### ISSUE TITLE
Closing the program doesn't kill its respective DynamicLOD.exe process.

### ISSUE THREAD

**Issue by Smiths76245** [Fragtality/DynamicLOD#2] opened 2023-12-18 00:54 UTC
Hi, thank you for making this fantastic program. I have noticed that closing the program doesn't 'fully' close it out unless I force quit from Task Manager. 

Running Windows 10 21H2 19043.3208 , process is excluded from Defender.

**Comment by Fragtality** [comment] 2023-12-18 09:35
All manual and automatic Ways to close the Program (not equal closing Window) work as intended.

**Closed as completed by Fragtality** 2023-12-18 09:35 UTC
